import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}> <div className="w-full h-auto">
     <div className="container flex flex-col mx-auto">
        <div className="nav">
          <Nav/>
            </div> 
            {children} 
         </div>
        </div>
      </body>
    </html>
  );
}
